image: docker:stable

services:
  - docker:dind
  - mongo:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - push

before_script:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD

build docker:
  stage: build
  script:
   - docker build -t $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA .
  only:
  - master

run unittest:
  stage: test
  script:
    - docker run -it $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA pipenv run test
  only:
  - master

push image to docker registry:
  stage: push
  script:
   - docker tag $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_REPOSITORY/$APP_NAME:latest
   - docker push $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA
   - docker push $DOCKER_REPOSITORY/$APP_NAME:latest
  only:
  - master

