

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build

run unittest:
  stage: test
  image: python:3.7.3-alpine3.8
  services:
    - mongo:latest
  script:
    - pip3.7 install pipenv
    - pipenv install
    - PROFILE=prod DB_HOST=mongo DB_PORT=27017 DB_NAME=uapi pipenv run test
  only:
  - master

build docker:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker build -t $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_REPOSITORY/$APP_NAME:latest
    - docker push $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_REPOSITORY/$APP_NAME:latest
  only:
  - master

