image: docker:stable

services:
  - docker:dind
  - mongo:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build

run unittest:
  image: python:3.7.3-alpine3.8
  stage: test
  script:
    - pip3.7 install pipenv
    - pipenv install
    - pipenv run test
  only:
  - master

build docker:
  stage: build
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
   - docker build -t $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA .
   - docker tag $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_REPOSITORY/$APP_NAME:latest
   - docker push $DOCKER_REPOSITORY/$APP_NAME:$CI_COMMIT_SHORT_SHA
   - docker push $DOCKER_REPOSITORY/$APP_NAME:latest
  only:
  - master

