kind: ImageStream
apiVersion: v1
metadata:
  name: "uapi"
spec:
  tags:
  - from:
      kind: DockerImage
      name: "docker-registry.default.svc:5000/uapi/uapi"
    name: "latest"
    importPolicy:
      scheduled: true
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "uapi"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/ppro-uapi"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "python:3.6"
        namespace: openshift
  output:
    to:
      kind: "ImageStreamTag"
      name: "uapi:latest"