---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "mongo"
  name: "mongo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mongo"
  template:
    metadata:
      labels:
        app: "mongo"
    spec:
      containers:
      - name: "mongodb"
        image: "mongo:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 27017
---
kind: Service
apiVersion: v1
metadata:
  name: "mongo"
spec:
  selector:
    app: "mongo"
  ports:
  - name: mongo
    port: 27017
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{uapi-secret}}"
type: Opaque
stringData:
  profile: prod
  db_host: "mongo"
  db_port: "27017"
  db_name: "uapi"
---
apiVersion: v1
kind: Service
metadata:
  name: "uapi"
spec:
  selector:
    app: "uapi"
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30081
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "uapi"
  name: "uapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "uapi"
  template:
    metadata:
      labels:
        app: "uapi"
    spec:
      containers:
      - name: "uapi"
        image: "docker.io/dimssss/uapi:latest"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
          - containerPort: 8080
        env:
        - name: PROFILE
          valueFrom:
            secretKeyRef:
              name: {{uapi-secret}}
              key: profile
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{uapi-secret}}
              key: db_host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: {{uapi-secret}}
              key: db_port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{uapi-secret}}
              key: db_name



